# Generated by Django 4.1.1 on 2022-09-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
            ],
        ),
    ]
